// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, cookies, fs, loadTrace, login, postLogin, request, userAgent;

  fs = require('fs');

  request = require('request');

  cheerio = require('cheerio');

  userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.103 Safari/537.36';

  cookies = request.jar();

  request = request.defaults({
    jar: cookies,
    followAllRedirects: true,
    headers: {
      'User-Agent': userAgent
    }
  });

  loadTrace = function(url) {
    return request(url, function(err, res, html) {
      if (!err) {
        return console.log(html);
      }
    });
  };

  postLogin = function() {
    var traceURL;
    traceURL = 'http://myneu.neu.edu/cp/ip/login?sys=was&url=https://prod-web.neu.edu/wasapp/TRACE25';
    return request(traceURL, function(err, res, html) {
      var data, name, new_cookie, pair, param, search_params, val, _i, _len;
      if (!err) {
        search_params = res['request']['uri']['search'].substring(1).split('&');
        data = {};
        for (_i = 0, _len = search_params.length; _i < _len; _i++) {
          param = search_params[_i];
          pair = param.split('=');
          name = pair[0];
          val = pair[1];
          if (name === "cookie") {
            new_cookie = request.cookie(unescape(val));
            cookies.setCookie(new_cookie, 'https://prod-web.neu.edu/CPIP/pickup_new.html');
          }
          if (name === "dest") {
            data['destination_url'] = unescape(val);
          }
        }
        return loadTrace(data['destination_url']);
      }
    });
  };

  login = function(uuid) {
    return request.post({
      url: 'https://myneu.neu.edu/cp/home/login',
      form: {
        user: process.env.NEU_USER,
        pass: process.env.NEU_PASS,
        uuid: uuid
      }
    }, function(err, res, html) {
      return postLogin();
    });
  };

  request('http://myneu.neu.edu/cp/home/displaylogin', function(err, res, html) {
    var $, uuid;
    if (!err) {
      $ = cheerio.load(html);
      uuid = $('script[language="javascript1.1"]').html().split('document.cplogin.uuid.value=\"')[1].split("\"")[0];
      login(uuid);
    }
  });

}).call(this);
